# if autoscaling parameter enabled is true, then replicaCount parameter is not used
replicaCount: 1
# if autoscaling parameter enabled is false, then replicaCount parameter is used
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetRAMUtilizationPercentage: 80

revisionHistoryLimit: 2
imagePullSecrets: registrypullsecret
namespace: default

image:
  repository: docker.zzdats.lv
  name: lx/demo
  tag: develop
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 500m
    memory: 100Mi
  requests:
    cpu: 10m
    memory: 50Mi
annotations:
  sidecar.istio.io/proxyCPU: '100m'
  sidecar.istio.io/proxyCPULimit: '300m'
  sidecar.istio.io/proxyMemory: '128Mi'
  sidecar.istio.io/proxyMemoryLimit: '256Mi'
service:
  type: ClusterIP
  internalPort: 80
  externalPort: 80
  readinessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30
    failureThreshold: 6
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 30

config:
  environments:
    PUBLIC_URL: https://lx-dev.zzdats.lv/
    # BASE_PATH is "/" by default
    BASE_PATH: /
    ENVIRONMENT: development
    SERVICE_URL: https://lx-dev.zzdats.lv/api/
    AUTH_URL: https://lx-dev.zzdats.lv/auth/
