apiVersion: v1
kind: Service
metadata:
  name: {{ template "lx-demo.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "lx-demo.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    version: {{ .Values.image.tag }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "lx-demo.name" . }}
    release: {{ .Release.Name }}
